### ISSUE TITLE
gids benchmark test runtime error when we specify page_size as 8K

### ISSUE THREAD

**Issue by gaowayne** [jeongminpark417/GIDS#25]
I am using L40s GPU

```
root@salab-hpedl380g11-01:~/wayne/gids/GIDS/evaluation# ./test1.sh
GIDS DataLoader Setting
GIDS:  True
CPU Feature Buffer:  True
Window Buffering:  True
Storage Access Accumulator:  True
Dataset: IGB
Setting the graph structure
dgl.heterograph init starting
{'created': ['csc'], 'not created': []}
dgl.heterograph init successful
SSD are not assigned
ssd list:  None
SSD index: 0
SQs: 255        CQs: 255        n_qps: 128
Ctrl sizes: 1
n pages: 524288
page size: 8192
num elements: 563200000000
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f8ec8010000       220020410000
HEREN
Finish Making Page Cache
Number of required storage accesses:  427.02499999999964
GPUassert: an illegal memory access was encountered /root/wayne/gids/GIDS/gids_module/gids_nvme.cu 458
Traceback (most recent call last):
  File "heterogeneous_train.py", line 312, in <module>
    track_acc_GIDS(g, category, args, device, labels, key_offset)
  File "heterogeneous_train.py", line 88, in track_acc_GIDS
    model = RSAGE(g.etypes, in_feats, args.hidden_channels,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

root@salab-hpedl380g11-01:~/wayne/gids/GIDS/evaluation# 
```

```
root@salab-hpedl380g11-01:~/wayne/gids/GIDS/evaluation# nvidia-smi
Tue Oct 29 04:17:32 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    Off |   00000000:8A:00.0 Off |                    0 |
| N/A   31C    P8             32W /  350W |      14MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2531      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
root@salab-hpedl380g11-01:~/wayne/gids/GIDS/evaluation# 
```

**Comment by gaowayne** [comment]
@jeongminpark417  buddy could you please add comment for this?
