### ISSUE TITLE
A question about 'pr_full.pt' file

### ISSUE THREAD

**Issue by WWWzq-01** [jeongminpark417/GIDS#6]
I use `homogenous_train.py` with igb_small datasets.
I meet a error when running the shell command below:
```shell
CUDA_VISIBLE_DEVICES=0  python homogenous_train.py --path /home/wzq/datasets/igb_datasets  --dataset_size small --epochs 1 --log_every 1000 --uva_graph 1 --GIDS --batch_size 4096  --data IGB --model_type sage --num_layers 3 --fan_out '10,5,5' --cache_size $((8*1024)) --num_ssd 1   --num_ele $((550*1000*1000*1024)) --page_size 4096 --emb_size 1024 --window_buffer --wb_size 16   --cpu_buffer --cpu_buffer_percent 0.2   --accumulator
```

the error:
```shell
Number of required storage accesses:  854.0499999999993
Traceback (most recent call last):
  File "/home/wzq/GIDS/evaluation/homogenous_train.py", line 305, in <module>
    track_acc_GIDS(g, args, device, labels)
  File "/home/wzq/GIDS/evaluation/homogenous_train.py", line 62, in track_acc_GIDS
    pr_ten = torch.load(args.pin_file)
  File "/home/wzq/miniconda3/envs/gids/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/wzq/miniconda3/envs/gids/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/wzq/miniconda3/envs/gids/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/nvme17/pr_full.pt'
```
Then I touch a file at /home/wzq/tmp/pr_full.pt and change the default value of args.`pin_file`. After that ,I run the shell again.Now the error is :
```shell
Traceback (most recent call last):
  File "/home/wzq/GIDS/evaluation/homogenous_train.py", line 305, in <module>
    track_acc_GIDS(g, args, device, labels)
  File "/home/wzq/GIDS/evaluation/homogenous_train.py", line 62, in track_acc_GIDS
    pr_ten = torch.load(args.pin_file)
  File "/home/wzq/miniconda3/envs/gids/lib/python3.9/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/wzq/miniconda3/envs/gids/lib/python3.9/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
```
Can you provide me with a template of the pin_file or tell me how to define/get this .pt file?

**Comment by jeongminpark417** [comment]
We have added the script to generate pr_full.pt (page-rank node ranking) inside the evaluation directory. The error occurs because the constant CPu buffer flag has been set without specifying the path to the page rank file (pr_full.pt).
